### ISSUE TITLE
Too few informations in readme leads to many mistakes

### ISSUE THREAD

**Issue by samieti02** [MIC-DKFZ/BraTS2017#13]
Hi dear Sir,

I've spent a lot of time trying to run the code, but without success. I always get mistakes. In fact:
The first one was about downsample. To solve it, i uploaded the lasagne package like this

`pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
`

Then the next one was an ImportError refering to this line code

`#from sklearn.cross_validation import KFold # this is deprecated -> bad, but need to keep it here for reproducibility`

If you know that a line code is deprecated, why do you keep it in the code? This is really annoying.
I have change the line code like

`from sklearn.model_selection import KFold`,

Hoping that it will not cause more mistakes

Then the next one was an error module about SimpleITK. I solved it with the following code
`conda install -c https://conda.anaconda.org/simpleitk SimpleITK`

Then i enter the command "python train_network.py 0",  and i got the error

```
raise IOError("%s not found." % path)
IOError: ../../BraTS17TrainingPre\id_name_conversion.txt not found.
```

I thought, maybe I should first execute the command "python run_preprocessing -m train", then i got

```
(brats_dkfz) C:\Users\me\BraTS2017_master>python run_preprocessing -m train
python: can't open file 'run_preprocessing': [Errno 2] No such file or directory
```

And i am in the good file
(brats_dkfz) C:\Users\me\BraTS2017_master\paths.py 	
	                                                           \predict_test_set.py 	
                                                                   \predict_val_set.py
                                        	                   \run_preprocessing.py
                                                                   \....

I create a python 2.7 environment  in anaconda with all the depencies, and also the batchgenerators.

Since I'm not an expert in Python, I don't know what to do anymore, how to proceed.
And I have to get the approach going, for further tests. Can you please help me?

Thanks

**Comment by FabianIsensee** [comment]
Hi,
> If you know that a line code is deprecated, why do you keep it in the code? This is really annoying.
I have change the line code like

Like I said in the comment: this is because I used it once a while back and wanted to keep the folds the same throughout my experiments so that I would be able to compare them properly. I know this is not ideal, but that was the way I did it back then. You must downgrade your version of sklearn and it will work again (pip install sklearn==some_version_number). Your workaround does not work because the new KFold works differently.

The file id_name_conversion.txt is created during preprocessing. You need to add the .py file extension to your command for it to work `C:\Users\me\BraTS2017_master>python run_preprocessing.py -m train`. As the error message said: there is no file named run_preprocessing.

You will not be able to run the training however. Windows is not supported by batchgenerators because python multithreading on windows is broken. All my repos were tested on ubuntu only.

I hope this helps!
Fabian
