### ISSUE TITLE
Questions about mlp and hidden layers in paper/code

### ISSUE THREAD

**Issue by samieti02** [MIC-DKFZ/BraTS2017#14]
Hello my dear Sir,

You said that "The ensemble consists of 15 MLPs, each with 3 hidden layers, 64 units per layer"
How/Where (in code) can we change/adjust the number of MLP/hidden layers/unitsPerLayer to build and train our own model?
And also how to plot the activation/features of the neurons or FMs, to clearly visualise, what is going on?
This kind of informations will hugely help people.

I also think that 15 for an ensemle is a bit high. Can you please explain us what 15 and not 10?

Thank you Sir!

**Comment by FabianIsensee** [comment]
Hi,
this repository is the segmentation part of the challenge. There is no code for the survival prediction available. To be honest, our survival prediction approach did not do so well (I did not put enough time and effort into it) so you might want to look at what others are doing.
If you want to plot the FM activations then you need to specify outputs in the theano graph for each feature map you want to plot. I cannot help you there because I have not worked with theano for a very long time.
Best,
Fabian
