### ISSUE TITLE
Why transpose the seg?

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#15]
@FabianIsensee Hi, sir. I am troubled by the line 219 in the train_network.py : seg = data_dict["seg_onehot"].astype(np.float32).transpose(0, 2, 3, 4, 1).reshape((-1, num_classes)). Why transpose the seg ?

**Comment by FabianIsensee** [comment]
because the 'class' dimension must be at the very end before reshaping to a vector. That was originally needed to make it work with crossentropy loss. You could write the dice loss differently so that it takes tensors but I am not working with that code anymore and am thus not going through the hassle
